HOSTS:
  server5:
    roles:
      - server
      - default
      - master
      - simp_server
      - nfs_server
      - el7
    platform:   el-7-x86_64
    box:        centos/7
    box_url:    https://vagrantcloud.com/puppetlabs/boxes/centos-7.0-64-nocm
    hypervisor: vagrant

  server4:
    roles:
      - simp_server
      - nfs_server
      - el6
    platform:   el-6-x86_64
    box:        centos/6
    box_url:    https://vagrantcloud.com/puppetlabs/boxes/centos-6.6-64-nocm
    hypervisor: vagrant

CONFIG:
  log_level: verbose
  type:      aio
  vagrant_memsize: 256
  # vb_gui: true
